import type { ArchitectureComponent } from '../../engine/types'

export const iroha1Components: ArchitectureComponent[] = [
  {
    id: 'client',
    name: 'Client',
    category: 'client',
    summary: "The external wallet or application Alice and Bob's accounts use to construct and sign transactions.",
    whatItDoes: "Constructs a transaction, signs it with the account owner's key, and submits it to Torii.",
    whyItExists:
      'Represents the external actor that originates a transaction before it enters the Iroha v1 peer pipeline.',
    inputs: ['user transfer intent'],
    outputs: ['signed transaction'],
    communicatesWith: ['torii'],
    relatedConcepts: ['torii-concept'],
    position: { x: 0, y: 60 },
  },
  {
    id: 'torii',
    name: 'Torii',
    category: 'gateway',
    summary: 'The primary gateway through which clients submit transactions and queries.',
    whatItDoes:
      'Accepts signed transactions and queries from clients and forwards transactions into the validation pipeline.',
    whyItExists: 'Provides a single, well-defined entry point into the Iroha v1 peer.',
    inputs: ['signed transaction'],
    outputs: ['transaction forwarded for stateless validation'],
    communicatesWith: ['client', 'stateless-validation'],
    relatedConcepts: ['torii-concept'],
    position: { x: 300, y: 60 },
  },
  {
    id: 'stateless-validation',
    name: 'Stateless Validation',
    category: 'validation',
    summary: 'Checks transaction structure and signature format without consulting blockchain state.',
    whatItDoes:
      'Validates transaction structure and signature format before any state-dependent checks occur.',
    whyItExists:
      'Rejects malformed or badly signed transactions early, without needing to consult the World State View.',
    inputs: ['transaction forwarded from Torii'],
    outputs: ['structurally valid transaction'],
    communicatesWith: ['torii', 'mst-processor'],
    relatedConcepts: ['stateless-validation-concept'],
    position: { x: 600, y: 60 },
  },
  {
    id: 'mst-processor',
    name: 'MST Processor',
    category: 'validation',
    summary: "The Multisignature Transaction Processor, which collects signatures until an account's quorum is met.",
    whatItDoes:
      'Holds partially signed transactions and releases them once the required account signature quorum is reached.',
    whyItExists:
      'Allows transactions that require multiple signatures to wait for quorum without blocking the rest of the pipeline. For this MVP transaction the quorum is already satisfied, so the transaction passes straight through.',
    inputs: ['structurally valid transaction'],
    outputs: ["transaction that has met its account's signature quorum"],
    communicatesWith: ['stateless-validation', 'peer-communication-service'],
    relatedConcepts: ['mst-processor-concept'],
    position: { x: 900, y: 60 },
  },
  {
    id: 'peer-communication-service',
    name: 'Peer Communication Service',
    category: 'networking',
    summary: 'Handles peer-level transaction routing and communication.',
    whatItDoes: 'Routes the fully signed transaction toward the ordering pipeline.',
    whyItExists:
      'Provides the peer-to-peer communication layer that moves transactions between pipeline stages and peers.',
    inputs: ['fully signed transaction'],
    outputs: ['transaction routed to the Ordering Service'],
    communicatesWith: ['mst-processor', 'ordering-service'],
    relatedConcepts: ['peer-communication-service-concept'],
    position: { x: 1200, y: 60 },
  },
  {
    id: 'ordering-service',
    name: 'Ordering Service',
    category: 'ordering',
    summary: 'Collects transactions and groups them into proposals.',
    whatItDoes: 'Accepts incoming transactions and batches them into a proposal.',
    whyItExists: 'Establishes an ordering of transactions before they undergo state-dependent validation.',
    inputs: ['routed transaction'],
    outputs: ['proposal'],
    communicatesWith: ['peer-communication-service', 'proposal'],
    relatedConcepts: ['ordering-service-concept'],
    position: { x: 1200, y: 340 },
  },
  {
    id: 'proposal',
    name: 'Proposal',
    category: 'other',
    summary: 'A batch of transactions waiting to undergo state-dependent validation.',
    whatItDoes:
      'Represents the current batch of transactions, treated for this MVP as containing only the one transfer transaction, awaiting stateful validation.',
    whyItExists:
      'Acts as an explicit waypoint between the Ordering Service and Stateful Validation so the transaction pipeline has a clear intermediate state.',
    inputs: ['batched transactions from the Ordering Service'],
    outputs: ['proposal submitted for stateful validation'],
    communicatesWith: ['ordering-service', 'stateful-validation'],
    relatedConcepts: ['proposal-concept'],
    position: { x: 900, y: 340 },
  },
  {
    id: 'stateful-validation',
    name: 'Stateful Validation',
    category: 'validation',
    summary: 'Checks transaction validity against the current blockchain state.',
    whatItDoes:
      'Validates each proposal transaction against the World State View, checking account existence, balances, and permissions.',
    whyItExists:
      'Ensures only transactions that are valid against current blockchain state are carried forward into the committed block.',
    inputs: ['proposal', 'World State View'],
    outputs: ['stateful-valid transaction'],
    communicatesWith: ['proposal', 'verified-proposal'],
    relatedConcepts: ['stateful-validation-concept', 'world-state-view-concept'],
    position: { x: 600, y: 340 },
  },
  {
    id: 'verified-proposal',
    name: 'Verified Proposal',
    category: 'other',
    summary: 'The subset of a proposal containing transactions that successfully passed stateful validation.',
    whatItDoes: 'Holds the transactions that passed stateful validation and are ready for block creation.',
    whyItExists: 'Provides an explicit waypoint distinguishing validated transactions from the original proposal.',
    inputs: ['stateful-valid transaction'],
    outputs: ['verified proposal submitted to the Block Creator'],
    communicatesWith: ['stateful-validation', 'block-creator'],
    relatedConcepts: ['verified-proposal-concept'],
    position: { x: 300, y: 340 },
  },
  {
    id: 'block-creator',
    name: 'Block Creator',
    category: 'other',
    summary: 'Creates a candidate block from the verified proposal.',
    whatItDoes: 'Assembles the verified proposal into a candidate block for consensus.',
    whyItExists: 'Produces the concrete block artifact that peers vote on during YAC consensus.',
    inputs: ['verified proposal'],
    outputs: ['candidate block'],
    communicatesWith: ['verified-proposal', 'yac-consensus'],
    relatedConcepts: ['block-creator-concept'],
    position: { x: 300, y: 620 },
  },
  {
    id: 'yac-consensus',
    name: 'YAC Consensus',
    category: 'consensus',
    summary: 'Yet Another Consensus — the algorithm peers use to agree on the candidate block.',
    whatItDoes: 'Coordinates peer agreement on the candidate block.',
    whyItExists:
      'Ensures all peers commit the same block, even though this MVP does not visualize the full peer network.',
    inputs: ['candidate block'],
    outputs: ['consensus-agreed block'],
    communicatesWith: ['block-creator', 'commit'],
    relatedConcepts: ['yac-consensus-concept'],
    position: { x: 600, y: 620 },
  },
  {
    id: 'commit',
    name: 'Commit',
    category: 'storage',
    summary: 'Finalizes the consensus-agreed block and persists it, updating the World State View.',
    whatItDoes:
      'Commits the consensus-agreed block, persisting it and applying its transactions to the World State View.',
    whyItExists: "Marks the point at which a transaction's effects become part of the durable blockchain state.",
    inputs: ['consensus-agreed block'],
    outputs: ['committed block', 'updated World State View'],
    communicatesWith: ['yac-consensus', 'blockstore-wsv'],
    relatedConcepts: ['world-state-view-concept', 'blockstore-concept'],
    position: { x: 900, y: 620 },
  },
  {
    id: 'blockstore-wsv',
    name: 'Blockstore / World State View',
    category: 'storage',
    summary: 'Persistent storage for committed blocks and the current blockchain state used by queries and validation.',
    whatItDoes:
      'Stores committed blocks (Blockstore) and maintains current account balances, accounts, assets, and permissions (World State View).',
    whyItExists: 'Provides the durable source of truth that both queries and future transaction validation rely on.',
    inputs: ['committed block'],
    outputs: ['persisted block history', 'current account balances'],
    communicatesWith: ['commit'],
    relatedConcepts: ['blockstore-concept', 'world-state-view-concept'],
    position: { x: 1200, y: 620 },
  },
]
